//@module shortjsdoc
// this is the main class for all the application
// utilities for rendering jsdoc data generated by jsdocgenerator1 js-indentator plugin
// using backbone. The user should provide with underscore templates. 
// @class AbstractView @extend Backbone.View @module shortjsdoc
// @author: sgurin

//@class Application 
//@constructor Application @param {Object} data
var Application = function(data)
{
	this.textFormat = 'markdown'; 
	
	this.templates = shortjsdoc; //global variable given b templates.js

	// this.parser = jsindentator.styles.shortJsDoc; 
	this.data = data; 

	this.maker = new JsDocMaker();
	this.maker.data = data;
	this.maker.postProccessBinding();

	// jQuery('body').addClass('container-fluid');

	// if(jQuery('#mainHeader').size()===0)
	// {
	// 	jQuery('body').append('<div id="mainHeader"></div>'); 
	// }
	// this.$mainHeader = jQuery('#mainHeader'); 

	if(jQuery('#mainContainer').size()===0)
	{
		jQuery('body').append('<div id="mainContainer"></div>'); 
	}
	this.$containerEl = jQuery('#mainContainer'); 
};

_(Application.prototype).extend({

	start: function()
	{		
		this.router = new JsDocRouter(this);
		Backbone.history.start();
		var navigateTo = Backbone.history.getHash() || 'index'; 
		Backbone.history.navigate(navigateTo, {trigger: true});
	}

,	showView: function(view)
	{
		this.applicationView = this.applicationView || new ApplicationView(this); 
		this.currentView = view;
		this.$containerEl.empty();
		this.applicationView.renderIn(this.$containerEl);
		// view.afterRender(); 
	}
	
,	refreshWithNewModel: function(data)
	{
		this.data = data; 
		Backbone.history.navigate('#index', {trigger: true}); 
		this.showView(this.currentView);
	}

,	showErrorView: function(s) 
	{
		this.$containerEl.empty().append('<h1>'+s+'</h1>'); 
	}

});

//@method start an application loading it with given data. @static
//@param data the output of passing jsindentator JsDocMaker. 
Application.start = function(data)
{
	var app = new Application(data); 
	app.start();
}; 
