//this is the main class for all the application
// utilities for rendering jsdoc data generated by jsdocgenerator1 js-indentator plugin
// using backbone. The user should provide with underscore templates. 
// @author: sgurin

//@class Application 
//@constructor Application @param {Object} data
var Application = function(data)
{
	this.templates = shortjsdoc; //global variable given b templates.js

	// this.parser = jsindentator.styles.shortJsDoc; 
	this.data = data; 

	this.maker = new JsDocMaker();
	this.maker.data=data;
	this.maker.postProccessBinding();

	if(jQuery('#mainHeader').size()===0)
	{
		jQuery('body').append('<div id="mainHeader"></div>'); 
	}
	this.$mainHeader = jQuery('#mainHeader'); 

	if(jQuery('#mainContainer').size()===0)
	{
		jQuery('body').append('<div id="mainContainer"></div>'); 
	}
	this.$containerEl = jQuery('#mainContainer'); 
};

_(Application.prototype).extend({

	start: function()
	{		
		this.router = new JsDocRouter(this);
		Backbone.history.start();
		var navigateTo = Backbone.history.getHash() || 'index'; 
		Backbone.history.navigate(navigateTo, {trigger: true});
	}

,	showView: function(view)
	{
		this.currentView = view;
		var template = this.templates[view.template]; 
		if(template)
		{			
			var html = template.apply(view, []); 
			view.$el.html(html);
			this.$containerEl.empty().append(view.$el); 
		}
		this.updateHeader();
	}

,	updateHeader: function()
	{
		if(!this.headerView)
		{
			this.headerView = new HeaderView(this); 
			this.headerView.render();
		}
	}
,	refreshWithNewModel: function(data)
	{
		this.data = data; 
		Backbone.history.navigate('#index', {trigger: true}); 
		this.showView(this.currentView);
	}

,	showErrorView: function(s) 
	{
		this.$containerEl.empty().append('<h1>'+s+'</h1>')
	}

});

//@method start an application loading it with given data. @static
//@param data the output of passing jsindentator JsDocMaker. 
Application.start = function(data)
{
	var app = new Application(data); 
	app.start();
}; 
