
component_depth: 1
languages:
- name: js
  production:
    exclude:
      - /html/lib*
      - /html/data*
      - /html/all*
      - /html/template-output.js
      - /lib
      - /test/lib
      - /test/node-test-project
      - /tools
      - /vendor-jsdoc